fixtures:
  repositories:
    stdlib:  'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    java:    'git://github.com/vmware/vmware-java.git'
    staging: 'git://github.com/nanliu/puppet-staging.git'
